### ISSUE TITLE
Conversion Of annotations to COCO format

### ISSUE THREAD

**Issue by engrjav** [FOD-UNOmaha/FOD-data#2]
We have FOD-A data sets in two resolutions 
1. Original (400x400)
2. Pascal Voc (300x300)

In the original annotations are numbered with images starting from frame_000000.PNG till the number of images in that folder. 
For example the class "battery" has four folders (1, 2, 2a, 3) and each folder starts with frame_000000.PNG. 

However, in the Pascal VOC format , the frames are numbered as frame_000000.jpg to 033792.jpg. 

I have two questions:

1) If i want to convert original format to coco format, do i need to rename images/ annotations in original format for each category to avoid repitition of image names?
2) If i select Pascal Voc format(300x300) dataset and convert its annotations, according to my understanding due to lower resolution, i should get less AP for my algorithm.  Do you think it will be a bad idea to use pascal voc format ? if yes why is it available?

Thanks in advance

**Comment by LeeSamoyed** [comment]
I have a similar problem, I got better results using the VOC format dataset. Have you tried using the VOC data format for training ?

**Comment by engrjav** [comment]
@LeeSamoyed  yes . I also used VOC to get better results
